CREATE TABLE [dbo].[awardcompiledreleasetable] (

	[date] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[id] varchar(8000) NULL, 
	[item_classification_description] varchar(8000) NULL, 
	[item_classification_id] varchar(8000) NULL, 
	[item_classification_scheme] varchar(8000) NULL, 
	[item_classification_uri] varchar(8000) NULL, 
	[item_description] varchar(8000) NULL, 
	[item_id] varchar(8000) NULL, 
	[quantity] int NULL, 
	[item_unit_name] varchar(8000) NULL, 
	[status] varchar(8000) NULL, 
	[supplier_countryName] varchar(8000) NULL, 
	[supplier_locality] varchar(8000) NULL, 
	[supplier_postalCode] varchar(8000) NULL, 
	[supplier_region] varchar(8000) NULL, 
	[supplier_streetAddress] varchar(8000) NULL, 
	[supplier_contact_telephone] varchar(8000) NULL, 
	[supplier_identifier_id] varchar(8000) NULL, 
	[supplier_legalName] varchar(8000) NULL, 
	[supplier_scheme] varchar(8000) NULL, 
	[supplier_uri] varchar(8000) NULL, 
	[supplier_name] varchar(8000) NULL, 
	[title] varchar(8000) NULL, 
	[award_value_amount] int NULL, 
	[award_value_currency] varchar(8000) NULL, 
	[tender_title] varchar(8000) NULL, 
	[tender_id] varchar(8000) NULL, 
	[buyer_name] varchar(8000) NULL
);